// Default Campaign Playbook

import { Playbook } from './types';

export const defaultPlaybook: Playbook = {
  id: 'default-campaign',
  name: 'Default Campaign Workflow',
  description: 'Standard campaign creation workflow with content generation',
  phases: [
    {
      id: 'briefing',
      name: 'Campaign Briefing',
      description: 'Initial campaign briefing and requirements gathering',
      agentId: 'briefing-agent',
      requiredInputs: ['campaignId', 'userId'],
      outputKey: 'briefing',
      maxRetries: 2,
      timeout: 60000,
    },
    {
      id: 'content-generation',
      name: 'Content Generation',
      description: 'Generate campaign content based on briefing',
      agentId: 'content-agent',
      dependsOn: ['briefing'],
      requiredInputs: ['briefing'],
      outputKey: 'content',
      maxRetries: 3,
      timeout: 120000,
    },
    {
      id: 'visual-creation',
      name: 'Visual Creation',
      description: 'Create visual assets for the campaign',
      agentId: 'visual-agent',
      dependsOn: ['content-generation'],
      requiredInputs: ['content'],
      outputKey: 'visuals',
      maxRetries: 3,
      timeout: 180000,
    },
    {
      id: 'review',
      name: 'Content Review',
      description: 'Review and validate campaign content',
      agentId: 'review-agent',
      dependsOn: ['content-generation', 'visual-creation'],
      requiredInputs: ['content', 'visuals'],
      outputKey: 'review',
      maxRetries: 2,
      timeout: 60000,
    },
    {
      id: 'optimization',
      name: 'Campaign Optimization',
      description: 'Optimize campaign for target audience',
      agentId: 'optimization-agent',
      dependsOn: ['review'],
      requiredInputs: ['review', 'content', 'visuals'],
      outputKey: 'optimized',
      maxRetries: 2,
      timeout: 90000,
    },
    {
      id: 'finalization',
      name: 'Campaign Finalization',
      description: 'Finalize campaign and prepare for deployment',
      agentId: 'finalization-agent',
      dependsOn: ['optimization'],
      requiredInputs: ['optimized'],
      outputKey: 'final',
      maxRetries: 1,
      timeout: 60000,
    },
  ],
};
